# 이어드림스쿨 5기의 알고리즘 및 코딩테스트 스터디
# today_solved() 봇
# -- 문제풀이 인증 시간 알림을 위한 자동 메시지 출력봇

name: today_solved()

on:
# push시, 자동 메시지 현상 방지하기 위해 비활성화
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  # 수동 실행 기능 추가
  workflow_dispatch:
  # 한국시간 기준으로 오후 10시에 봇 작동
  schedule:
    - cron: "0 13 * * *"

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_01 }}
        content: "오늘의 문제풀이를 올려주세요! 마감까지 2시간 남았습니다."

# build 구문 삭제
